blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/cerberus-iam/auth-ui/blob/main/README.md
    about: Please check the documentation first
  - name: Discussions
    url: https://github.com/cerberus-iam/auth-ui/discussions
    about: Use discussions for questions and general help
